# Generated by Django 5.0.6 on 2024-06-08 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_count',
        ),
        migrations.AddField(
            model_name='wallet',
            name='trans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wallet'),
        ),
    ]
